name: 💅 Lint Test

on:
    push:
        branches:
            - "main"
        paths:
            - '**.go'
            - '**.mod'
    pull_request:
        branches:
          - "main"
        paths:
            - '**.go'
            - '**.mod'
    workflow_dispatch:

jobs:
    lint:
        name: Lint Test
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read
            security-events: write
        steps:
            -
                name: Set up Go
                uses: actions/setup-go@v4
                with:
                    go-version:  '>=1.20'
            -
                name: Checkout the repository
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -
                name: Run golangci-lint
                uses: golangci/golangci-lint-action@v3
                with:
                    version: v1.52.2
                    args: --timeout 5m
                    working-directory: .